### ISSUE TITLE
prepend inline-form does not work

### ISSUE THREAD

**Issue by ghost** [libracoder/bootstrap4-offline-docs#1]
![capture](https://user-images.githubusercontent.com/19872729/36065036-fc2effbe-0ea5-11e8-8b45-c96719759ec4.PNG)
![d](https://user-images.githubusercontent.com/19872729/36065037-fc5801f2-0ea5-11e8-9991-cd576efe730b.PNG)

I have screenshoot of the latest documentation, but your documentation may be too old.
Please update it.

**Comment by libracoder** [comment]
The documentation has been updated
