### ISSUE TITLE
New version (v4.4) is live

### ISSUE THREAD

**Issue by 7FFY** [libracoder/bootstrap4-offline-docs#7]
First of all I would like to say thank you for this repo as it's super useful.
This is not a real issue, everything is working correctly but just an update for you that bootstrap is now at version 4.4.
I have no idea if this changes a lot of things from the previous version but I just wanted to let you know.

**Comment by libracoder** [comment]
Thanks you for reaching out to me. 
I will be updating it before the end of the week

**Comment by mrizkimaulidan** [comment]
> Thanks you for reaching out to me.
> I will be updating it before the end of the week

How do you make an offline docs? please share with us! :smiley:

**Comment by libracoder** [comment]
Its a gruesome process that involves a lot of regex. Maybe i will do a post on it sometime soon.
